### ISSUE TITLE
Full Spawning urls scan 

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/dataset-viewer#1087]
Currently we have urls scan implemented for first 100K rows [here ](https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runners/split/opt_in_out_urls_scan_from_streaming.py)
We need to do it for full dataset but there could be some concerns:
- Full scan could take too much time for big datasets (Like [laion](https://huggingface.co/datasets/laion/laion2B-en)) and we have a task configured [here](https://github.com/huggingface/datasets-server/blob/bdda4ed42c3f884995917ae6e7575ef67e338f48/services/worker/src/worker/executor.py#L121) that kills long running jobs that can prevent Full scan to do not finish
- We have a response size validation [here](https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runner.py#L470) which can lead to a database error in case of having big content (Too much opt in/out urls) to store

Approach 1:
Run full dataset scan in one single job
Will need the following actions:
- Implement custom timeout configurations to kill "long running jobs" i.e We could have a WORKER_MAX_JOB_DURATION_SECONDS value for split-opt-in-out-urls-scan Job set up to 10 hrs and for other jobs 20 min (as  it is currently)
- Store the content response (or maybe only opt in/out urls list) in an external storage. It was suggested by @severo  to store it on a parquet file (see thread https://github.com/huggingface/datasets-server/pull/1044#discussion_r1173625223). I think it could be a good idea but will need to think where to store the file (Maybe https://datasets-server.huggingface.co/assets? Another branch in each repository like we actually do for parquets https://huggingface.co/datasets/<dataset>/tree/refs%2Fconvert%2Fparquet? )
- In case we dont need yet to show the list of opt in/out urls, we can skip previous step and only store number of urls see sample: https://datasets-server.huggingface.co/opt-in-out-urls-scan?dataset=laion/laion2B-en&config=laion--laion2B-en&split=train

<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

key  |  value
-- | --
urls_columns | […]
~~opt_in_urls~~ | []
~~opt_out_urls~~ | […]
num_opt_in_urls | 0
num_opt_out_urls | 1853
num_urls | 100000
num_scanned_rows | 100000
has_urls_columns | true

</div>

</div>

Approach 2:
Run full scan in separated Jobs and store results in separated cache entries
Will need the following actions:
- Add support in current datasets-server architecture to have another level of granularity https://github.com/huggingface/datasets-server/blob/main/libs/libcommon/src/libcommon/processing_graph.py#L12 maybe "batch" that will have an start_row and an end_row or offset and limit. So we scan the dataset by batches and store its result in a cache entry for each batch. At the end we could have a "dataset" aggregated Job that will give us the summarized result of previous responses e.g:

**Batch one:  offset:0 , limit:1000**

<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

key  |  value
-- | --
urls_columns | […]
~~opt_in_urls~~ | []
~~opt_out_urls~~ | […]
num_opt_in_urls | 0
num_opt_out_urls | 10
num_urls | 1000
limit | 1000
offset | 0

</div>

</div>

**Batch two:  offset:1000 , limit:1000**

<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

key  |  value
-- | --
urls_columns | […]
~~opt_in_urls~~ | []
~~opt_out_urls~~ | […]
num_opt_in_urls | 4
num_opt_out_urls | 5
num_urls | 50
limit | 1000
offset | 1000

</div>

</div>
`
Aggregated response:
`
<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

<div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

key  |  value
-- | --
urls_columns | […]
~~opt_in_urls~~ | []
~~opt_out_urls~~ | […]
num_opt_in_urls | 4 (0 + 4)
num_opt_out_urls | 15 (10 + 5) 
num_urls | 1050 = (1000 from batch one and 50 from batch two)

</div>

</div>

- The only problem with this approach is that we could still have sometimes issues with db storage limitation (e.g a few opt in/out urls but really long text)

**Comment by AndreaFrancis** [comment]
I would go for the first approach since it is the least invasive for our current architecture and also will solve the issue with mongodb limitation. 
Let me know what do you think @huggingface/datasets-server
cc. @julien-c  I think the way we store the opt in/out urls list also depends on how we plan to show it in the viewer.
In the initial phase if it is not needed yet, we could start running full scan for all dataset but only store the counters.

**Comment by severo** [comment]
Some comments:

> Implement custom timeout configurations to kill "long running jobs" i.e We could have a WORKER_MAX_JOB_DURATION_SECONDS value for split-opt-in-out-urls-scan Job set up to 10 hrs and for other jobs 20 min (as it is currently)

We don't need specific code for that because we can dedicate pods to this job (with `WORKER_ONLY_JOB_TYPES="split-opt-in-out-urls-scan"`) and set a specific value to `WORKER_MAX_JOB_DURATION_SECONDS`.

>  In the initial phase if it is not needed yet, we could start running full scan for all dataset but only store the counters.

I think we can do that for now, because anyway, we will need to refresh every entry regularly, maybe every month. Indeed:  the opted-in and opted-out URLs we store on our side will possibly be outdated when data from spawning.ai is updated.

> cc. @julien-c I think the way we store the opt in/out urls list also depends on how we plan to show it in the viewer

@julien-c @gary149 we could have a specific cell display when the URL is opted-out or opted-in. what do you think? is it worth the effort for now?

**Comment by lhoestq** [comment]
I don't think we need to show the opt-outs in the viewer. We can imagine letting the dataset owner download a big CSV with all the opt-out URLs (and their location in the dataset). In that case I think we can do approach 1 indeed and save it on S3 somewhere ?

Maybe we can even ask dataset owners request it by email until we make a proper download button ?

(and I think it's more convenient for dataset owners to get a CSV instead of Parquet - without strong opinion though)
(it's also fine to have one single file since the URLs scanning job can run on one single process - since it's bounded by the API calls)

**Comment by AndreaFrancis** [comment]
> We don't need specific code for that because we can dedicate pods to this job (with WORKER_ONLY_JOB_TYPES="split-opt-in-out-urls-scan") and set a specific value to WORKER_MAX_JOB_DURATION_SECONDS.

Yes but we will have tp remove "all" worker https://github.com/huggingface/datasets-server/blob/main/chart/env/prod.yaml#L237 since it could include jobs from "split-opt-in-out-urls-scan" of specify the others runners without spawning one.

> (and I think it's more convenient for dataset owners to get a CSV instead of Parquet - without strong opinion though)

Agree, maybe it will be simpler/friendly for the owner to get the information in csv

> (it's also fine to have one single file since the URLs scanning job can run on one single process - since it's bounded by the API calls)

Agree, maybe one csv file with columns "url", "row_idx", "opt_in", "opt_out" as it is in Spawning response

**Comment by severo** [comment]
> Yes but we will have to remove "all" worker https://github.com/huggingface/datasets-server/blob/main/chart/env/prod.yaml#L237 since it could include jobs from "split-opt-in-out-urls-scan" of specify the others runners without spawning one.

Yes, you're right, I hadn't thought about it. Even so: I think it's ok

**Comment by AndreaFrancis** [comment]
Full scan will be implemented initially for small datasets (Considering that a dataset is "small" when the server was able to get its parquet files in `"refs/convert/parquet"`).
To achieve it, these steps are needed:

- [ ] Implement partition granularity level in datasets-server --> In progress https://github.com/huggingface/datasets-server/pull/1213
- [ ] Separate logic of image URL columns inspect from scanning --> In progress https://github.com/huggingface/datasets-server/pull/1256
- [ ] Create step `"partition-opt-in-out-urls-scan"` to be a `PartitionJobRunner` and scan rows based on partition_start/end (Not sure if we will still read rows using datasets library in streaming mode or change reading from parquet files, wdyt @severo @lhoestq?)
- [ ] Change step `"split-opt-in-out-urls-scan"` to `"split-opt-in-out-urls-count"` to only summarize partitions data into a split (Same as `config-opt-in-out-urls-count `and `dataset-opt-in-out-urls-count`) 

@huggingface/datasets-server let me know if this sounds like a plan, note that probably "partitions" pattern could be used in the future when we need a "full dataset read".

**Comment by severo** [comment]
I agree that it would be better to use parquet to get the URLs

**Comment by lhoestq** [comment]
sounds good to me !

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
Should we close? I don't think we will do it in the near future.

**Comment by severo** [comment]
Closing. Feel free to reopen if it makes sense.
