### ISSUE TITLE
Load a parquet export with `pyarrow.parquet.ParquetDataset`

### ISSUE THREAD

**Issue by lhoestq** [huggingface/dataset-viewer#1694]
`read()` fails because it tries to load the `index.duckdb` file as a parquet file

```python
from huggingface_hub import HfFileSystem
import pyarrow.parquet as pq

ds = pq.ParquetDataset("datasets/squad@~parquet", filesystem=HfFileSystem()).read()
```

raises

```
ArrowInvalid: Could not open Parquet input source 'datasets/squad@~parquet/plain_text/train/index.duckdb': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```

Shall we rename the `index.duckdb` file ? I think we can try renaming it to `_index.duckdb` or `.index.duckdb`

-----------------------

Also `read_pandas()` also fails (this is what pandas uses when calling `pd.read_parquet`)

```python
from huggingface_hub import HfFileSystem
import pyarrow.parquet as pq

df = pq.ParquetDataset("datasets/squad@~parquet", filesystem=HfFileSystem()).read_pandas()
```

raises

```
EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64dd05ce-3f58691a7b2e8fd67c76425b)

Entry Not Found for url: https://huggingface.co/api/datasets/squad/tree/~parquet/_common_metadata?expand=True.
Tree Entry not found: _common_metadata
```

**Comment by severo** [comment]
Or switch to refs/convert/duckdb

**Comment by lhoestq** [comment]
What would be the best way to move the duckdb indexes (to a new branch or a new directory) ?

Shall we increment the version of the duckdb-index job with the new location and implement an "update" step in case the index is already there just to move it ?

**Comment by severo** [comment]
First: do we want to move/rename the file inside the same branch (`refs/convert/parquet`) or move to a different branch (`refs/convert/duckdb`). btw: we now convert all the splits to duckdb (before: we only did it for text datasets).

What do you think @julien-c @gary149?

**Comment by albertvillanova** [comment]
Also: https://huggingface.slack.com/archives/C0311GZ7R6K/p1686665484050679

And I repeat what I said there:
> I think it is important that the directory containing the parquet files for a specific config+split, just contains the parquet files and no other files.

**Comment by severo** [comment]
see #2413

**Comment by AndreaFrancis** [comment]
Now that the index file has been removed, I  see another issue:
![image](https://github.com/huggingface/datasets-server/assets/5564745/a15f3dd2-3b9f-4fd5-b91a-998369738e64)
`ValueError: Directory name did not appear to be a partition: v1.1.0`

**Comment by severo** [comment]
maybe it's specific to this dataset and config name?

<img width="689" alt="Capture d’écran 2024-03-08 à 20 02 13" src="https://github.com/huggingface/datasets-server/assets/1676121/217f2582-7b96-4d58-b1ad-9a58940ff72e">

**Comment by severo** [comment]
> Now that the index file has been removed, I see another issue:

Let's open another issue for this @AndreaFrancis?
