### ISSUE TITLE
switch hardcoded `MAX_NUM_STRING_LABELS` from 30 to some relative number (n_unique / n_samples)

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/dataset-viewer#1953]

**Comment by polinaeterna** [comment]
unstale

**Comment by severo** [comment]
btw @polinaeterna: setting a priority (P0/P1/P2) disables the stale bot. It's what I did last week, since we want to implement this feature.

**Comment by polinaeterna** [comment]
I just though that ideally we would have a way to configure the viewer somehow, for example in readme's yaml. 
I imagine we can have an additional `"viewer"` or smth key where users can set some configurable parameters. For example, if a column is string or category, which subset to show by default (not always we want to show the one first by alphabet).

Yes, for categories we can set `ClassLabel` column in `dataset_info` but this changes the underlying data type from string to int (@lhoestq am i right here?) which might be unwanted.

wdyt @huggingface/datasets-server ?

**Comment by lhoestq** [comment]
Maybe we should show the default subset first ? It can be marked using `default: true` in YAML.

> Yes, for categories we can set ClassLabel column in dataset_info but this changes the underlying data type from string to int (@lhoestq am i right here?) which might be unwanted.

Yes correct, and it also requires to specify the types of all the columns which is not ideal. Not sure yet if such configuration would be used a lot though

**Comment by polinaeterna** [comment]
> Maybe we should show the default subset first ? It can be marked using default: true in YAML.

also an option, we have an issue for that https://github.com/huggingface/datasets-server/issues/2541
should it be changed on the front-end or on our side in datasets-server? if the latter, i guess just the order of configs in `dataset-config-names` step should be changed?

**Comment by severo** [comment]
Done.
