### ISSUE TITLE
Rate-limit the updates?

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2279]
See https://huggingface.co/datasets/lunaluan/chatbox8_history/commits/main: two commits are created every minute (47K commits). This dataset is currently blocked manually (https://github.com/huggingface/datasets-server/pull/2184).

Should we create a rule to automatically limit the number of updates per hour/day? Note that doing so might imply changing how we handle the "revision". If we decide to process a specific commit, all the steps should use the same commit, even if new ones have appeared since.

**Comment by severo** [comment]
If we rate-limit, we could propose different modes:
- limited
- full

**Comment by severo** [comment]
Another way is to deprioritize the dataset by moving the job date to the future, depending on the time between the last two/three commits + filtering on the date when picking a job, so that dates in the future are ignored.

**Comment by lhoestq** [comment]
Is it possible to say that a job should wait e.g. 10min before being run ? And if a commit happens in the meantime, the job is deleted and replaced with the new job with the same wait penalty.

**Comment by severo** [comment]
Hopefully #2933 fixes most of the issues.

I think we need a fix though: the autoscaling is based on the number of jobs. But we need to remove the blocked datasets from the count.

**Comment by severo** [comment]
> I think we need a fix though: the autoscaling is based on the number of jobs. But we need to remove the blocked datasets from the count.

good news, it's not necessary, because if the dataset is updated while it's blocked (which is often the case: blocked for 1 hours, 1 commit every 5 minutes), all the cache entries + all the pending jobs are deleted -> it does not influenciate the metrics anymore.

**Comment by lhoestq** [comment]
(until backfill does its job maybe ?)

**Comment by severo** [comment]
no, because it only creates two jobs (dataset-config-names and dataset-filetypes, the root steps) and they are never run while the dataset is blocked.

**Comment by severo** [comment]
hmmm, I changed my mind and opened #2945. I think it's urgent, to fix the autoscaling

**Comment by severo** [comment]
fixed
