### ISSUE TITLE
Add "modality" tags in /hub-cache

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2455]
Could be: `image` and `audio`, to start with.

Related issues:
- https://github.com/huggingface/datasets-server/pull/2454 (libraries).
- https://github.com/huggingface/datasets-server/issues/2408 (tasks).
- internal: https://github.com/huggingface/moon-landing/issues/7557

Previous issue:
- https://github.com/huggingface/datasets-server/issues/561 (column types)

**Comment by julien-c** [comment]
also maybe `format: {json, csv, parquet, imagefolders, etc}` (not sure if this is the same issue though)
