### ISSUE TITLE
Support large_string as indexable column in FTS?

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/dataset-viewer#2613]
I've seen there are some datasets like [afg1/litscan-epmc-subset](https://huggingface.co/datasets/afg1/litscan-epmc-subset) and [baber/USPTO](https://huggingface.co/datasets/baber/USPTO) that have large_strings but does not support FTS because of this condition https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runners/split/duckdb_index.py#L77 
Should we add large_string as part of the condition?

**Comment by severo** [comment]
yes, it seems logical to support both

**Comment by AndreaFrancis** [comment]
Done by #2755
