### ISSUE TITLE
Rename this project `dataset-viewer`

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2650]
idea from here: https://huggingface.slack.com/archives/C02V51Q3800/p1711555601697509?thread_ts=1711535232.998799&cid=C02V51Q3800 (internal)

> First is that I think nobody has any idea it’s related to the viewer (keep pointing people to it when they ask)

Making it clear that this code "powers the frontend feature":
- it would help when providing support (this project sends the data and the errors to the dataset viewer)
- it could foster more contributions: people contribute to see the features they want on HF (think Croissant for example)

---

## Name, repo, text, docs, variables

- [x] change the repo's name - everything will be redirected (https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository), so: we should be able to do it at any time
- [x] in this repo, change all the names / variables / docs to replace `datasets-server` with `dataset-viewer`, `Datasets Server` with `Dataset viewer`, etc. -> #2663, #2665
- [x] Slack channels
- [x] Notion pages
- [x] Grafana charts -> https://grafana.huggingface.tech/dashboards/f/e_I3EQ0Vz/dataset-viewer
- [x] https://huggingface.co/spaces/datasets-maintainers/datasets-server-admin-ui -> https://huggingface.co/spaces/datasets-maintainers/dataset-viewer-admin-ui (with redirection)
- [x] observable notebooks
- [x] Miro
- [x] kibana
- [x] https://github.com/orgs/huggingface/teams/datasets-server -> @huggingface/dataset-viewer
- [x] https://github.com/huggingface/moon-landing (https://github.com/huggingface/moon-landing/pull/9520 then https://github.com/huggingface/dataset-viewer/pull/2665)
- [x] https://github.com/huggingface/datasets (https://github.com/huggingface/datasets/pull/6785)
- [x] huggingface blogposts?

## Follow-ups

- https://github.com/huggingface/dataset-viewer/issues/2669
- https://github.com/huggingface/dataset-viewer/issues/2668
- https://github.com/huggingface/dataset-viewer/issues/2666
- https://github.com/huggingface/dataset-viewer/issues/2667

**Comment by julien-c** [comment]
in favor!

**Comment by severo** [comment]
Note that we already have the good old https://github.com/huggingface/datasets-viewer. Not to be confused with the new proposed https://github.com/huggingface/dataset-viewer without `s` :)

**Comment by severo** [comment]
TODO:

- [ ] in this repo: change all the names / variables / docs to replace `datasets-server` with `dataset-viewer`, `Datasets Server` with `Dataset viewer`, etc.
- [ ] in other repos (moon-landing, infra, etc.) fix the URLs, texts, docs, variable names
- [ ] change the repo's name (is this the last step?)
- [ ] change the URLs
  - https://datasets-server.huggingface.co -> https://dataset-viewer.huggingface.co
  - https://datasets-server.us.dev.moon.huggingface.tech -> https://dataset-viewer.us.dev.moon.huggingface.tech
  and redirect old URLs to new URLs

**Comment by severo** [comment]
The principal issue will be to change the API domain (datasets-server.huggingface.co -> dataset-viewer.huggingface.co). Not urgent though, nobody will complain meanwhile.

Also: renaming the docs (/docs/datasets-server -> /docs/dataset-viewer)

**Comment by julien-c** [comment]
the API domain we don't really need to change it no?

**Comment by julien-c** [comment]
the docs yes i would advocate to change them (and create a redirect in moon or Cloudfront)

**Comment by severo** [comment]
> the API domain we don't really need to change it no?

sure, it would be a lot simpler. Anyway, we can also change it later if we want. Same for all the infra-related stuff.
