### ISSUE TITLE
Tutorial about how to start/run my own local dataset server.

### ISSUE THREAD

**Issue by ANYMS-A** [huggingface/dataset-viewer#2654]
Hey, 
    I'm new to the dataset server and rookie in the Web field. I wanted to build my own dataset server however, is there any tutorial that can guide me to build my own dataset server?

Many Thanks

**Comment by severo** [comment]
Hi! You can look at the [developer guide](https://github.com/huggingface/datasets-server/blob/main/DEVELOPER_GUIDE.md). Feel free to comment here if you have an issue to make it work, or if something is unclear. We would love your feedback to improve the onboarding.
