### ISSUE TITLE
Handling dataset redirects

### ISSUE THREAD

**Issue by PeterAJansen** [huggingface/dataset-viewer#2688]
Currently datasets-server doesn't appear to handle dataset redirects, and gives an error. 

For example: 
- Querying `datasets` endpoints with the dataset `squad` works

- Querying `datasets-server` endpoints with the dataset `squad` gives an "unknown error"
- Querying `datasets-server` endpoints with a random dataset name (e.g. `xyz2309348`) gives an expected response (e.g. dataset unknown/doesn't exist)
- Querying `datasets-server` endpoints with the redirected name (`rajpurkar/squad`) works.

**Comment by severo** [comment]
The dataset-viewer only knows the last repository name, if it has been renamed once or more. For example, `squad` was renamed `rajpurkar/squad`, and the previous entries for `squad` in the database have been deleted, and new ones were created for `rajpurkar/squad`. As we don't check if the repo was renamed, asking for `dataset=squad` returns an error.

To support this, if the dataset has not been found in the database, we should request the Hub to get the current name of the repo (in the example: `rajpurkar/squad`) and look again if the dataset exists in the database.

**Comment by severo** [comment]
also: 

> Querying datasets-server endpoints with the dataset squad gives an "unknown error"

^ this is a bug

**Comment by severo** [comment]
With #3035, it now returns 404 with `{"error":"The dataset has been renamed. Please use the current dataset name."}`. At least, this bug is fixed.

**Comment by severo** [comment]
Let's close. We don't plan to support repositories redirection in this API.
