### ISSUE TITLE
Update numba

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/dataset-viewer#2698]
Numba dependency was introduced to the exact 0.56.4 version in: https://github.com/huggingface/dataset-viewer/pull/1026/files#diff-e127bcf65702533dbd7e316815e4b116552c3adef5d4d50db54147d430d868edR24
- #1026

If there is not a strong requirement to use that specific version, we should update it.

**Comment by albertvillanova** [comment]
@lhoestq I am wondering why you introduced this dependency.

**Comment by lhoestq** [comment]
I don't remember honestly :/ maybe because a test was failing because one of the image or audio dependency requires it

**Comment by albertvillanova** [comment]
Thanks for your reply. It is true that it was long ago...
