### ISSUE TITLE
parquet-and-info worker fails if a parquet file is empty

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2709]
Reported here: 

https://huggingface.co/datasets/Asap7772/persona_gpt4_paired_margin1_allsplit/discussions/1#66187c367d8c2cd6fbce4a19

Error is:

```
 {"error": "Could not read the parquet files: Some index in row_group_indices is 0, which is either < 0 or >= num_row_groups(0)"}
```

I think the issue is with file `test_questions-00000-of-00001.parquet`:

<img width="839" alt="Capture d’écran 2024-04-12 à 10 09 47" src="https://github.com/huggingface/dataset-viewer/assets/1676121/bc561541-b2f0-4e20-8621-9672866d3de9">

The file is: https://huggingface.co/datasets/Asap7772/persona_gpt4_paired_margin1_allsplit/blob/main/data/test_questions-00000-of-00001.parquet

**Comment by severo** [comment]
cc @lhoestq for viz

**Comment by AndreaFrancis** [comment]
Fixed by https://github.com/huggingface/dataset-viewer/pull/2791
