### ISSUE TITLE
Raise "DatasetGenerationError" instead of "UnexpectedError"

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2723]
And give the details to the users. It generally helps them fix the underlying error by giving the underlying error message.

See https://huggingface.co/datasets/ibrahimhamamci/CT-RATE/discussions/56#661d1ce1689f5231501a0f9b for example.

related to #1443

**Comment by severo** [comment]
it's fixed too, right @AndreaFrancis?

**Comment by AndreaFrancis** [comment]
It should be after I deploy https://github.com/huggingface/dataset-viewer/pull/2796 (I will do it right now)
