### ISSUE TITLE
Improve the message for DatasetWithScriptNotSupportedError

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2742]
Now we have a CLI tool to convert a script dataset to a data-only one (parquet). See https://github.com/huggingface/datasets/releases/tag/2.19.0
<img width="676" alt="Capture d’écran 2024-04-23 à 11 41 10" src="https://github.com/huggingface/dataset-viewer/assets/1676121/0a90c9fc-47c5-4266-bf6e-07b2c29986a6">

We should reflect that in all the error messages for DatasetWithScriptNotSupportedError: https://github.com/search?q=repo%3Ahuggingface%2Fdataset-viewer+%22raise+DatasetWithScriptNotSupportedError%22&type=code, and propose the user to use the CLI to convert the dataset. Ideally with a link to a doc that shows how to do it (I think the doc page should lie in https://github.com/huggingface/datasets/tree/main/docs, see https://github.com/huggingface/datasets/issues/6830).

**Comment by severo** [comment]
cc @albertvillanova

**Comment by albertvillanova** [comment]
I can start working on this once this was merged:
- https://github.com/huggingface/datasets/pull/6831

**Comment by severo** [comment]
It's live: https://huggingface.co/docs/datasets/main/en/cli

but it's not on the default docs page because it shows the docs for 2.19.0 (https://huggingface.co/docs/datasets/v2.19.0/en/index)

**Comment by albertvillanova** [comment]
I think this is a duplicate of:
- #2692
