### ISSUE TITLE
Rows Post Processing Error

### ISSUE THREAD

**Issue by Helw150** [huggingface/dataset-viewer#2782]
Seeing a re-emergence of this issue on a recently release Parquet Dataset: https://github.com/huggingface/dataset-viewer/issues/602

```
Server error while post-processing the split rows. Please report the issue.
Error code:   RowsPostProcessingError
```

https://huggingface.co/datasets/parler-tts/mls_eng_10k

**Comment by severo** [comment]
Yes, it's a known issue: https://huggingface.co/datasets/parler-tts/mls_eng_10k/discussions/1

-> https://github.com/huggingface/dataset-viewer/issues/2584

Hopefully we have a solution soon. cc @polinaeterna @albertvillanova  if you have more details
