### ISSUE TITLE
Do not convert Opus audio files to WAV

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/dataset-viewer#2818]
As suggested by @severo, we could avoid the conversion of Opus audio files to WAV: https://github.com/huggingface/dataset-viewer/pull/2811#issuecomment-2113015400

Indeed, according to https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs, it's a well-supported codec among browsers (see "Browser compatibility" in the Opus table).

Beware:
> Safari supports Opus in the `<audio>` element only when packaged in a CAF file, and only on macOS High Sierra (10.13) or iOS 11.

Overall:
> Opus is a good all-around audio codec for use in your web applications, and can be used for any audio tasks you have in mind.

**Comment by Airop** [comment]
Hey, I would like to work on that!
