### ISSUE TITLE
Align CI and production environments

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/dataset-viewer#2819]
While investigating an issue (see https://github.com/huggingface/dataset-viewer/pull/2792#issuecomment-2110295795), I discovered that our CI and production environments are misaligned, and thus the CI does not strictly test what will happen in production.

For example, the `libsndfile1` package:
- CI uses `1.0.31` version
- Production uses `1.2.0` version

Another example, the `ffmpeg` package:
- CI uses `4.4.2` version
- Production uses `5.1.4` version

Also note that the Linux distributions are different:
- CI uses **Ubuntu**
  - It uses "ubuntu-latest", currently `ubuntu-22.04`
- Production uses **Debian**
  - Currently, it uses `python:3.9.18-slim` (EDIT: ~~`docker.io/nginx:1.25.3`~~) image, from `debian:12-slim` (bookworm)

We should align CI and production environments.

**Comment by severo** [comment]
Good idea.

Just a detail, I don't think the production is based on nginx, but on python: https://hub.docker.com/_/python/

https://github.com/huggingface/dataset-viewer/blob/8e68cfe15a3c649ae4d69281e894d444c1c7568e/services/api/Dockerfile#L3

**Comment by albertvillanova** [comment]
Thanks for the correction: I got confused with the image of the reverse-proxy.

I am editing the description of this issue.
