### ISSUE TITLE
Refer to Hub docs in dataset-viewer docs

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2845]
See https://www.reddit.com/r/huggingface/comments/1csdrfn/comment/l50jfkx/

> It would be useful if the "dataset viewer" doc page referenced the one you gave. 

From https://huggingface.co/docs/datasets-server, it's not easy to see the docs for https://huggingface.co/docs/hub/datasets-data-files-configuration or https://huggingface.co/docs/hub/datasets-adding#file-formats or https://huggingface.co/collections/datasets-examples/image-dataset-6568e7cf28639db76eb92d65.

We should make it a lot clearer in https://huggingface.co/docs/datasets-server that we document the **API** while https://huggingface.co/docs/hub/datasets documents the Datasets Hub, including how to configure the dataset.

What do you think @julien-c @stevhliu @huggingface/dataset-viewer?

**Comment by ppbrown** [comment]
More specifically,
https://huggingface.co/docs/hub/en/datasets-viewer-configure

really needs to reference https://huggingface.co/docs/hub/datasets-image 

In particular, the ability to add metadata for the images, that gets displayed by the viewer, was something I had difficulty finding up til now.

**Comment by julien-c** [comment]
> What do you think @julien-c @stevhliu @huggingface/dataset-viewer?

yes agreed, let's improve it

**Comment by stevhliu** [comment]
To make it clearer, maybe you can add something like the below to Dataset viewer's `index.md`?

The dataset viewer is a lightweight web API for visualizing and exploring all types of datasets - computer vision, speech, text, and tabular - stored on the Hugging Face [Hub](https://huggingface.co/datasets).
Look at the Hub's [Datasets](https://huggingface.co/docs/hub/datasets) documentation to learn more about managing datasets from the Hub's web-based interface.
