### ISSUE TITLE
Move /webhook to its own service

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2848]
In order to investigate https://github.com/huggingface/dataset-viewer/issues/2395, we can separate /webhook from the rest of the endpoints served by the API service. Indeed, it's by far the slowest one to respond (15% of the requests take > 700ms, 5% > 7s !) compared to the other ones (the worst one, /info, has 15% > 60ms, 5% > 600ms).

Moving /webhook to its own service is similar to what we did for /search or /rows. Note that we might want to have its own set of nodes, in which case we need to add a node groups here: https://github.com/huggingface/infra/blob/main/projects/hub/00-aws/variables/hub-aws-prod-us-east-1.tfvars

**Comment by AndreaFrancis** [comment]
Implemented by https://github.com/huggingface/dataset-viewer/pull/2849
