### ISSUE TITLE
Improve error handling (message, hints, link ot the docs)

### ISSUE THREAD

**Issue by neoneye** [huggingface/dataset-viewer#2864]
# Problem

The dataset viewer shows this error when I open [my public dataset repo](https://huggingface.co/datasets/neoneye/base64-decode-v1).

My repo contains both `data.jsonl` and python files for regenerating the `data.jsonl` file.

```
Cannot get the config names for the dataset.
Error code:   ConfigNamesError
Exception:    DataFilesNotFoundError
Message:      No (supported) data files found in neoneye/base64-decode-v1
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/job_runners/dataset/config_names.py", line 73, in compute_config_names_response
                  config_names = get_dataset_config_names(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/inspect.py", line 347, in get_dataset_config_names
                  dataset_module = dataset_module_factory(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1904, in dataset_module_factory
                  raise e1 from None
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1885, in dataset_module_factory
                  return HubDatasetModuleFactoryWithoutScript(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1270, in get_module
                  module_name, default_builder_kwargs = infer_module_for_data_files(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 597, in infer_module_for_data_files
                  raise DataFilesNotFoundError("No (supported) data files found" + (f" in {path}" if path else ""))
              datasets.exceptions.DataFilesNotFoundError: No (supported) data files found in neoneye/base64-decode-v1
```

![Screenshot 2024-05-28 at 17 25 42](https://github.com/huggingface/dataset-viewer/assets/147971/26c957cb-1138-47d5-bba1-043af8dcbd26)

# Kludgy solution

If I removing all python files for regenerating the dataset, so the repo only contains `data.jsonl` and `README.md` and no other files. Then the dataset viewer works. However I don't like discarding my dataset generator.

I tried moving my python files to a dir named `scripts`, but that breaks the Dataset Viewer.

# Found a solution after several attempts

In the `README.md` of my project I have added this
```
configs:
  - config_name: default
    data_files:
      - split: train
        path: data/data.jsonl
```

I have moved the `data.jsonl` to the path `data/data.jsonl`.

Now the Dataset Viewer is working.

I'm not sure if this is the correct way to specify that my `data.jsonl` is the file that holds my data.

# Ideal solution

When the dataset viewer is showing an error message, then improve on the error message so it's easier to resolve the error.

The huggingface documentation page, [datasets-viewer-configure](https://huggingface.co/docs/hub/datasets-viewer-configure), if it explain best practice for naming the `data` file, so the Dataset Viewer is working. Eventual workarounds when the Dataset Viewer isn't working.

**Comment by severo** [comment]
Thanks for all the details. Indeed, we have several issues around the same topic: improve the error message to provide hints that help fix the dataset viewer.

**Comment by severo** [comment]
Done (will be in prod today)
