### ISSUE TITLE
Create a new error code (retryable) for "Consistency check failed"

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2875]
See https://huggingface.co/datasets/cis-lmu/Taxi1500-RawData/viewer/mal_Mlym

It currently gives this error:

```
Consistency check failed: file should be of size 13393376 but has size 11730856 ((…)a9b50f83/mal_Mlym/taxi1500/dataset.arrow). We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument. If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
```

discussion here: https://huggingface.co/datasets/cis-lmu/Taxi1500-RawData/discussions/1

We should catch the exception and raise a new error, that should be a "retryable" error.

**Comment by severo** [comment]
@albertvillanova @lhoestq could you confirm that this error should be retried?

**Comment by lhoestq** [comment]
idk, does it work if you retry ?

**Comment by severo** [comment]
It does not seem so. Maybe it simply indicates a broken file?

**Comment by severo** [comment]
OK, the issue was with the data file!
