### ISSUE TITLE
Feature Request: Freeze/Restart/Log Viewer Option for Users.

### ISSUE THREAD

**Issue by kargaranamir** [huggingface/dataset-viewer#2876]
### Description
I've noticed a couple of things that could make using the dataset-viewer better. Here are three simple suggestions based on what I've experienced:

### Suggestions
1. **Keeping Parquet Viewer Steady**
    - Issue: Every time I tweak something like the content in the README, the Parquet viewer resets and tries to rebuild it.
    - Solution Idea: Add a "freeze" button for users so it stays where it is.

2. **Easier Viewer Restart**
    - Issue: It's definitely annoying to have to restart the viewer manually all the time for the dataset-viewer maintainers.
    - Solution Idea: Create a "restart" button for users so they can quickly reset the viewer.

3. **Log**
    - Issue: Just having access to the log of dataset-viewer errors would be very helpful. But the current log report is too abstract!
    - Solution Idea: Improve the error log report for better understanding.

Thanks for considering these suggestions!

**Comment by severo** [comment]
> Keeping Parquet Viewer Steady

Indeed. We're working on it at https://github.com/huggingface/dataset-viewer/issues/2757

> Easier Viewer Restart

it's not annoying at all; it's a way for us to detect bugs. The normal workflow never requires the user to refresh manually. We're thankful when people open discussions to report issues.

> Log

Yes, indeed, we have a bunch of issues open to give more details in some cases: https://github.com/huggingface/dataset-viewer/issues?q=is%3Aissue+is%3Aopen+label%3A%22error+handling%22

**Comment by kargaranamir** [comment]
Thanks for the response. I'm glad to hear that all of them are somehow considered to be done in before.
