### ISSUE TITLE
Store `started_at` or duration info in cached steps too

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/dataset-viewer#2892]
This would help to better monitor how much time a step take, especially depending on dataset size, so that we can see how certain changes influence processing speed and make more informed decisions about these changes and our size limits (see https://github.com/huggingface/dataset-viewer/issues/2878). Especially useful for duckdb and statistics step.

I can work on this if you think it's useful (I think it is) and don't break any logic.

**Comment by severo** [comment]
good idea

**Comment by severo** [comment]
Note that it will help for https://github.com/huggingface/dataset-viewer/issues/2279, because we will be able to compute thresholds based on the compute spent for a specific dataset/user/org in the last... N hours/days.
