### ISSUE TITLE
detect more modalities

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2898]
Currently, we only detect and report "audio", "image" and "text".

Ideally, we would have: 

<img width="318" alt="Capture d’écran 2024-06-11 à 16 07 20" src="https://github.com/huggingface/dataset-viewer/assets/1676121/1a21dfff-5c78-45bd-8baf-de1f4b203b6a">

See https://github.com/huggingface/moon-landing/pull/9352#discussion_r1634909052 (internal)

---

TODO:

- [x] text
- [x] image
- [x] audio
- [ ] video: detect extensions in the repo files: mp4, avi, mkv, etc.
- [ ] 3d: detect extensions in the repo files: ply, glb, gltf, etc.
- [ ] tabular <- I'm not sure what it means. Only numbers? 
- [ ] geospatial. Let's include both raster (e.g., satellite images) and vector (e.g. latitude/longitud points) even if they have few things in common and are generally in different datasets. Several strategies: extensions (geojson, geoparquet, geotiff, etc), column types (see geoarrow), column names? (longitude, latitude, geom), column contents (see wkt/wkb - but I don't think we want to look inside the data itself)
- [ ] time-series: columns with type `Sequence(Value(float32))` which are not embeddings (filter against the column name: `emb`?)

---

Currently, we only check the features given by the datasets library (`dataset-info` step).

For the strategy based on looking at the file extensions, it's a bit imprecise (eg: if the YAML contains `data_files: data.csv` and the repo also contains a video, the dataset will be marked as video, while the video is ignored). We can bear with it for now, I think.
Should we also detect repos that contain images or audio files but are not supported by the datasets library / the viewer?

**Comment by julien-c** [comment]
P0 no?:)

**Comment by severo** [comment]
TODO:

- [x] text
- [x] image
- [x] audio
- [ ] video: detect extensions in the repo files: mp4, avi, mkv, etc.
- [ ] 3d: detect extensions in the repo files: ply, glb, etc.
- [ ] tabular <- I'm not sure what it means. Only numbers? 
- [ ] geospatial. Let's include both raster (e.g., satellite images) and vector (e.g. latitude/longitud points) even if they have few things in common and are generally in different datasets. Several strategies: extensions (geojson, geoparquet, geotiff, etc), column types (see geoarrow), column contents (see wkt/wkb), column names? (longitude, latitude, geom)
- [ ] time-series: columns with type `Sequence(Value(float32))` which are not embeddings (filter against the column name: `emb`?)

**Comment by severo** [comment]
For the repo scan, we could do it in a new step, eg: `dataset-filetypes`, with a response as:

```json
[
  {
    "extension": ".ply",
    "archived_in": ".zip",
    "count": 153,
    "size": 23456843215,
    "partial": true
  },
  {
    "extension": ".ply",
    "count": 6168,
    "size": 23453215,
  },
  {
    "extension": ".glb",
    "count": 251,
    "size": 138468351
  },
  {
    "extension": ".md",
    "count": 1,
    "size": 1735
  }
]
```

Fields:
- `extension`: the file extension
- `count`: the number of files
- `size`: the total size of the files (uncompressed?)
- `archived_in`: the extension of the archive if the files were compressed: zip, tar, etc.
- `partial`: if the size and count are computed on part of the files (I think we will set limits)


Another option would be to check only the presence of every file type without computing stats. I have the intuition that it would not cost less, and it would be a lot poorer. Maybe `size` is not needed, though.

wdyt @lhoestq?

**Comment by severo** [comment]
Examples of datasets for every modality



3d:
- https://huggingface.co/datasets/tfnn/MESHY.AI_800_GLB_3D-Assets_Categorised_and_Labelled

**Comment by julien-c** [comment]
tabular = some/most of the columns are numerical?

**Comment by lhoestq** [comment]
You have the size info for free when listing files from the hub.

Listing files in the repo and files in ZIP archives sounds good to me. Later we can also include TAR but it's more work (it's slow to list files in a TAR archive and requires to download the whole file) and only concerns we dataset do far, for which we already have the image / audio modalities info from the feature types

**Comment by severo** [comment]
I think we can remove the size in `dataset-filetypes`, as it's something loosely related to the data (as the Parquet files for example can have a very different size). So:

```json
[
  {
    "extension": ".md",
    "count": 1,
  },
  {
    "extension": ".ply",
    "count": 6168,
  },
  {
    "extension": ".glb",
    "count": 251,
  },
  {
    "extension": ".ply",
    "archived_in": ".zip",
    "count": 153,
    "partial": true
  }
]
```

Fields:
- `extension`: the file extension
- `count`: the number of files
- `archived_in`: the extension of the archive if the files were compressed: zip, tar, etc.
- `partial`: if the size and count are computed on part of the files (I think we will set limits)

**Comment by severo** [comment]
OK: most of the modalities will be detected thanks to https://github.com/huggingface/dataset-viewer/pull/2909

Remaining:
- tabular
- time series

The heuristics to detect these two modalities would rely on Features.
 
For tabular, it could be:
- no "media" features (Audio / Image)
- at least two numerical features

For timeseries, it could be:
- at least one column with type Sequence(Value(float32)) which are not embeddings (filter against the column name: emb?)
^ not sure if it will match many datasets

Is it OK @lhoestq?

**Comment by lhoestq** [comment]
> ^ not sure if it will match many datasets

not sure either, we can try and refine if necessary
