### ISSUE TITLE
Async tests using anyio are skipped after including pytest-memray

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/dataset-viewer#2901]
Async tests using anyio are currently skipped. See: https://github.com/huggingface/dataset-viewer/actions/runs/9464138411/job/26070809625
```
tests/test_authentication.py ssssssssssssssssssssssssssssssssssssssssssssss

=============================== warnings summary ===============================
  /home/runner/.cache/pypoetry/virtualenvs/libapi-QfqNi3gs-py3.9/lib/python3.9/site-packages/_pytest/python.py:151: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
  You need to install a suitable plugin for your async framework, for example:
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
    - pytest-twisted
    warnings.warn(PytestUnhandledCoroutineWarning(msg.format(nodeid)))

tests/test_authentication.py::test_no_external_auth_check
  /home/runner/.cache/pypoetry/virtualenvs/libapi-QfqNi3gs-py3.9/lib/python3.9/site-packages/pymongo/topology.py:498: RuntimeWarning: coroutine 'test_no_external_auth_check' was never awaited
...
```

After investigation, I found that the issue arose after including pytest-memray by PR:
- https://github.com/huggingface/dataset-viewer/pull/2863
- The issue is caused when passing `--memray` to `pytest`: https://github.com/huggingface/dataset-viewer/blob/04f89d8a76e73874c9198c940ad2e61fe71f6f76/tools/PythonTest.mk#L7

I have reported the issue to pytest-memray team:
- https://github.com/bloomberg/pytest-memray/discussions/101#discussioncomment-9738673
- https://github.com/bloomberg/pytest-memray/issues/119

**Comment by severo** [comment]
Let's remove `--memray` I think. I don't think we need it (it only shows a report of the four more memory-consuming tests), we're more interested in specific tests using decorators like `@pytest.mark.limit_memory`, no?
