### ISSUE TITLE
[Modalities] Account for image URLs dataset for Image modality

### ISSUE THREAD

**Issue by lhoestq** [huggingface/dataset-viewer#2970]
right now datasets like https://huggingface.co/datasets/CaptionEmporium/coyo-hd-11m-llavanext are missing the Image modality even though they have image URLs

**Comment by apolinario** [comment]
Same for datasets with audio URLs, also properly identified by the dataset viewer: https://huggingface.co/datasets/multimodalart/test-audio-dataset
