### ISSUE TITLE
Inquiry about the Frontend Technologies Used in Dataset Viewer

### ISSUE THREAD

**Issue by jacob-rodgers-max** [huggingface/dataset-viewer#2990]
Hi team,

I'm currently researching the Dataset Viewer project and would like to understand more about the frontend technologies used. Specifically, I'm interested in knowing:

1. Which frontend framework is being utilized (e.g., React, Vue, etc.)?
2. Are there any specific libraries or components being used for UI (e.g., Material-UI, Ant Design)?
3. Any other notable frontend tools or technologies that are part of this project?

Your assistance in providing these details would be greatly appreciated. Thank you for your time and effort!

Best regards

**Comment by severo** [comment]
svelte, and tailwindcss.

**Comment by jacob-rodgers-max** [comment]
> svelte, and tailwindcss.

Thank you very much for your prompt and detailed response!
